### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by itryapitsin** [nickgravelyn/UnityTiled#2]
> DllNotFoundException: MonoPosixHelper
System.IO.Compression.DeflateStream..ctor (System.IO.Stream compressedStream, CompressionMode mode, Boolean leaveOpen, Boolean gzip)
(wrapper remoting-invoke-with-check) System.IO.Compression.DeflateStream:.ctor (System.IO.Stream,System.IO.Compression.CompressionMode,bool,bool)
System.IO.Compression.GZipStream..ctor (System.IO.Stream compressedStream, CompressionMode mode, Boolean leaveOpen)
(wrapper remoting-invoke-with-check) System.IO.Compression.GZipStream:.ctor (System.IO.Stream,System.IO.Compression.CompressionMode,bool)
UnityTiled.TileLayer..ctor (System.Xml.Linq.XElement element) (at Assets/UnityTiled/Editor/ObjectModel/TileLayer.cs:26)
UnityTiled.Layer.ReadLayer (System.Xml.Linq.XElement element) (at Assets/UnityTiled/Editor/ObjectModel/Layer.cs:36)
UnityTiled.Map..ctor (System.Xml.Linq.XDocument document, System.String mapDir) (at Assets/UnityTiled/Editor/ObjectModel/Map.cs:41)
UnityTiled.Map.FromFile (System.String file) (at Assets/UnityTiled/Editor/ObjectModel/Map.cs:50)
UnityTiled.TiledMapEditor.OnInspectorGUI () (at Assets/UnityTiled/Editor/TiledMapEditor.cs:38)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1231)
UnityEditor.DockArea:OnGUI()

This exception was thrown when I have been importing TMX-file. I'm using Unity 5.3.5 p8

PS: A quick fix is in https://www.assetstore.unity3d.com/en/#!/content/31902

**Comment by nickgravelyn** [comment]
Thanks for pointing this out. I'm on a Mac so I hadn't hit this. I will try to integrate Unity.IO.Compression into the library, not only to support Windows but also to support all compression modes for TMX maps.

**Comment by nickgravelyn** [comment]
Just fixed this up, so things should work fine on Windows now, hopefully!
